name: Docker Test

on:
  push:
    branches-ignore:
      - main
  # pull_request:
  #   branches:
  #     - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
      
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Build Docker image
      run: docker build -t blockful/external-resolver-contracts -f packages/contracts/Dockerfile packages/contracts

    - name: Start Docker container
      run: docker run -d --name external-resolver-contracts -p 8545:8545 blockful/external-resolver-contracts

    - name: Run install
      run: yarn
      
    - name: Run tests
      run: yarn test

    - name: Stop Docker container
      run: docker stop external-resolver-contracts
